questions.push({ level: 2, question: "calculate 7 + 5:",answer: "a = 7 + 5"})
questions.push({ level: 2, question: "calculate 7 + 5:",answer: "a = 7 + 5"})
questions.push({ level: 2, question: "calculate 7 + 5:",answer: "a = 7 + 5"})
questions.push({ level: 2, question: "calculate 7 + 5:",answer: "a = 7 + 5"})
questions.push({ level: 2, question: "calculate 7 + 5:",answer: "a = 7 + 5"})
questions.push({ level: 2, question: "calculate 7 + 5:",answer: "a = 7 + 5"})